"""
SQLAlchemy ORM Models for JAGA relational tables.
These models represent the staging and operational data,
while graph data is stored via Apache AGE.
"""

from sqlalchemy import Column, Integer, String, Float, Date, DateTime, Boolean, Text, ARRAY, JSON, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from datetime import datetime

from src.database import Base


class Participant(Base):
    """JKN Participant (Patient) master data"""
    __tablename__ = "participants"
    
    participant_id = Column(String(50), primary_key=True, index=True)
    name_hash = Column(String(64), nullable=False)  # Hashed for privacy
    age_band = Column(String(20))  # e.g., "18-40", "41-60"
    gender = Column(String(10))
    region_code = Column(String(20), index=True)
    employer_id = Column(String(50), nullable=True)
    registration_date = Column(Date)
    participant_status = Column(String(20), default="active")
    
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, onupdate=func.now())
    
    # Relationships
    claims = relationship("Claim", back_populates="participant")


class Provider(Base):
    """Healthcare provider (hospital, clinic, FKTP) master data"""
    __tablename__ = "providers"
    
    provider_id = Column(String(50), primary_key=True, index=True)
    provider_name = Column(String(200), nullable=False)
    facility_type = Column(String(50), index=True)  # RS Tipe A/B/C/D, Klinik, FKTP
    region_code = Column(String(20), index=True)
    ownership_type = Column(String(50))  # public/private
    bed_count = Column(Integer, nullable=True)
    services_offered = Column(ARRAY(String), nullable=True)
    accreditation_level = Column(String(20), nullable=True)
    
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, onupdate=func.now())
    
    # Relationships
    claims = relationship("Claim", back_populates="provider")


class Doctor(Base):
    """Doctor/physician master data"""
    __tablename__ = "doctors"
    
    doctor_id = Column(String(50), primary_key=True, index=True)
    doctor_name = Column(String(200), nullable=False)
    specialty = Column(String(100), index=True)
    license_number = Column(String(50), unique=True)
    affiliated_providers = Column(ARRAY(String), nullable=True)  # Array of provider_ids
    practice_start_date = Column(Date)
    
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, onupdate=func.now())
    
    # Relationships
    claims = relationship("Claim", back_populates="doctor")


class Claim(Base):
    """Healthcare claim records"""
    __tablename__ = "claims"
    
    claim_id = Column(String(50), primary_key=True, index=True)
    participant_id = Column(String(50), ForeignKey("participants.participant_id"), nullable=False, index=True)
    provider_id = Column(String(50), ForeignKey("providers.provider_id"), nullable=False, index=True)
    doctor_id = Column(String(50), ForeignKey("doctors.doctor_id"), nullable=True, index=True)
    
    claim_date = Column(Date, nullable=False, index=True)
    claim_amount = Column(Float, nullable=False)
    
    diagnosis_codes = Column(ARRAY(String), nullable=False)  # ICD-10 codes
    procedure_codes = Column(ARRAY(String), nullable=False)  # INA-CBG codes
    
    admission_date = Column(Date, nullable=True)
    discharge_date = Column(Date, nullable=True)
    length_of_stay = Column(Integer, nullable=True)
    
    claim_status = Column(String(20), default="approved", index=True)  # approved/rejected/pending
    
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, onupdate=func.now())
    
    # Relationships
    participant = relationship("Participant", back_populates="claims")
    provider = relationship("Provider", back_populates="claims")
    doctor = relationship("Doctor", back_populates="claims")
    risk_signals = relationship("RiskSignal", back_populates="claim")


class RiskSignal(Base):
    """Risk signals generated by detection engine"""
    __tablename__ = "risk_signals"
    
    signal_id = Column(Integer, primary_key=True, autoincrement=True)
    
    # What entity/network was flagged
    entity_type = Column(String(50), nullable=False, index=True)  # provider/doctor/participant/network
    entity_id = Column(String(50), nullable=False, index=True)
    
    # What type of risk
    signal_type = Column(String(50), nullable=False, index=True)  # CLONING/REFERRAL_CONCENTRATION/etc
    detection_method = Column(String(50), nullable=False)  # rule/statistical/graph/ml
    
    # Signal details
    signal_score = Column(Float, nullable=False)  # 0-100
    confidence = Column(Float, default=1.0)  # 0-1
    
    # Related entities
    related_claim_id = Column(String(50), ForeignKey("claims.claim_id"), nullable=True)
    related_entities = Column(JSON, nullable=True)  # JSON with related entity IDs
    
    # Evidence
    evidence = Column(JSON, nullable=True)  # JSON with supporting evidence
    explanation = Column(Text, nullable=True)  # Human-readable explanation
    
    # Metadata
    detected_at = Column(DateTime, server_default=func.now(), index=True)
    detection_run_id = Column(String(50), nullable=True)  # To group signals from same run
    
    # Relationships
    claim = relationship("Claim", back_populates="risk_signals")


class RiskNetwork(Base):
    """High-risk networks identified by graph analytics"""
    __tablename__ = "risk_networks"
    
    network_id = Column(String(50), primary_key=True, index=True)
    
    # Network composition
    entity_ids = Column(ARRAY(String), nullable=False)  # All entities in network
    entity_types = Column(JSON, nullable=False)  # Entity type breakdown
    
    # Risk assessment
    risk_score = Column(Float, nullable=False, index=True)  # 0-100
    risk_category = Column(String(20), nullable=False, index=True)  # LOW/MEDIUM/HIGH/CRITICAL
    primary_risk_type = Column(String(50), nullable=False)
    
    # Financial impact
    total_claim_amount = Column(Float, nullable=False)
    claim_count = Column(Integer, nullable=False)
    
    # Time period
    first_activity_date = Column(Date, nullable=False)
    last_activity_date = Column(Date, nullable=False)
    
    # Risk signals
    signal_ids = Column(ARRAY(Integer), nullable=True)  # Reference to RiskSignal IDs
    signal_breakdown = Column(JSON, nullable=True)  # Contribution by detection method
    
    # Explanation
    explanation = Column(Text, nullable=True)
    peer_comparison = Column(JSON, nullable=True)
    
    # Investigation status
    investigation_status = Column(String(20), default="queued", index=True)  # queued/in_progress/confirmed/dismissed
    assigned_to = Column(String(50), nullable=True)  # Investigator user ID
    
    # Metadata
    detected_at = Column(DateTime, server_default=func.now(), index=True)
    updated_at = Column(DateTime, onupdate=func.now())


class Investigation(Base):
    """Investigation records and decisions"""
    __tablename__ = "investigations"
    
    investigation_id = Column(Integer, primary_key=True, autoincrement=True)
    network_id = Column(String(50), ForeignKey("risk_networks.network_id"), nullable=False, index=True)
    
    # Investigator
    investigator_id = Column(String(50), nullable=False)
    investigator_name = Column(String(200))
    
    # Decision
    decision = Column(String(20), nullable=False)  # confirmed/dismissed/need_more_evidence
    confidence_level = Column(String(20), nullable=True)  # high/medium/low
    
    # Notes
    notes = Column(Text, nullable=True)
    dismissal_reason = Column(String(100), nullable=True)  # If dismissed
    
    # Feedback for ML
    helpful_signals = Column(ARRAY(String), nullable=True)  # Which signals were helpful
    feedback_score = Column(Integer, nullable=True)  # 1-5 rating
    
    # Timestamps
    started_at = Column(DateTime, nullable=False)
    completed_at = Column(DateTime, server_default=func.now())
    time_spent_minutes = Column(Integer, nullable=True)


class EntityFeature(Base):
    """Precomputed features for entities (for ML and analytics)"""
    __tablename__ = "entity_features"
    
    feature_id = Column(Integer, primary_key=True, autoincrement=True)
    
    entity_type = Column(String(50), nullable=False, index=True)
    entity_id = Column(String(50), nullable=False, index=True)
    
    time_window = Column(Integer, nullable=False)  # 30/90/365 days
    
    # Features stored as JSON for flexibility
    features = Column(JSON, nullable=False)
    
    # Peer group
    peer_group_id = Column(String(50), nullable=True, index=True)
    peer_statistics = Column(JSON, nullable=True)
    
    computed_at = Column(DateTime, server_default=func.now(), index=True)
