-- JAGA Database Schema Initialization
-- PostgreSQL + Apache AGE
-- Version: 1.0.0

-- Enable Apache AGE extension
CREATE EXTENSION IF NOT EXISTS age;
LOAD 'age';
SET search_path = ag_catalog, "$user", public;

-- Create AGE graph
SELECT * FROM ag_catalog.create_graph('jkn_graph');

-- Note: Relational tables will be created by SQLAlchemy ORM via Alembic migrations
-- This file documents the overall schema design

-- Table: participants
-- Stores JKN participant/patient master data
-- Columns: participant_id (PK), name_hash, age_band, gender, region_code, 
--          employer_id, registration_date, participant_status, created_at, updated_at

-- Table: providers  
-- Stores healthcare provider master data (hospitals, clinics, FKTP)
-- Columns: provider_id (PK), provider_name, facility_type, region_code,
--          ownership_type, bed_count, services_offered, accreditation_level,
--          created_at, updated_at

-- Table: doctors
-- Stores doctor/physician master data
-- Columns: doctor_id (PK), doctor_name, specialty, license_number,
--          affiliated_providers, practice_start_date, created_at, updated_at

-- Table: claims
-- Stores healthcare claim records
-- Columns: claim_id (PK), participant_id (FK), provider_id (FK), doctor_id (FK),
--          claim_date, claim_amount, diagnosis_codes, procedure_codes,
--          admission_date, discharge_date, length_of_stay, claim_status,
--          created_at, updated_at

-- Table: risk_signals
-- Stores risk signals generated by detection engine
-- Columns: signal_id (PK), entity_type, entity_id, signal_type, detection_method,
--          signal_score, confidence, related_claim_id (FK), related_entities,
--          evidence, explanation, detected_at, detection_run_id

-- Table: risk_networks
-- Stores high-risk networks identified by graph analytics
-- Columns: network_id (PK), entity_ids, entity_types, risk_score, risk_category,
--          primary_risk_type, total_claim_amount, claim_count, first_activity_date,
--          last_activity_date, signal_ids, signal_breakdown, explanation,
--          peer_comparison, investigation_status, assigned_to, detected_at, updated_at

-- Table: investigations
-- Stores investigation records and decisions
-- Columns: investigation_id (PK), network_id (FK), investigator_id, investigator_name,
--          decision, confidence_level, notes, dismissal_reason, helpful_signals,
--          feedback_score, started_at, completed_at, time_spent_minutes

-- Table: entity_features
-- Stores precomputed features for entities (for ML and analytics)
-- Columns: feature_id (PK), entity_type, entity_id, time_window, features,
--          peer_group_id, peer_statistics, computed_at

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_claims_participant ON claims(participant_id);
CREATE INDEX IF NOT EXISTS idx_claims_provider ON claims(provider_id);
CREATE INDEX IF NOT EXISTS idx_claims_doctor ON claims(doctor_id);
CREATE INDEX IF NOT EXISTS idx_claims_date ON claims(claim_date);
CREATE INDEX IF NOT EXISTS idx_claims_status ON claims(claim_status);

CREATE INDEX IF NOT EXISTS idx_risk_signals_entity ON risk_signals(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_risk_signals_type ON risk_signals(signal_type);
CREATE INDEX IF NOT EXISTS idx_risk_signals_detected ON risk_signals(detected_at);

CREATE INDEX IF NOT EXISTS idx_risk_networks_score ON risk_networks(risk_score);
CREATE INDEX IF NOT EXISTS idx_risk_networks_status ON risk_networks(investigation_status);
CREATE INDEX IF NOT EXISTS idx_risk_networks_category ON risk_networks(risk_category);

CREATE INDEX IF NOT EXISTS idx_entity_features_entity ON entity_features(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_entity_features_peer ON entity_features(peer_group_id);

-- Graph Schema (Apache AGE)
-- These are created dynamically via application code

-- Node Labels:
-- - :Participant {participant_id, age_band, gender, region}
-- - :Doctor {doctor_id, specialty, years_in_practice}
-- - :Provider {provider_id, provider_name, facility_type, region}
-- - :Claim {claim_id, claim_date, claim_amount, diagnosis_codes, procedure_codes, length_of_stay}

-- Edge Types:
-- - (:Participant)-[:VISITS {first_visit_date, last_visit_date, total_visits, total_amount}]->(:Provider)
-- - (:Doctor)-[:TREATS {first_treatment_date, last_treatment_date, treatment_count}]->(:Participant)
-- - (:Doctor)-[:WORKS_AT {affiliation_start_date, patient_count_at_provider}]->(:Provider)
-- - (:Participant)-[:GENERATES {claim_date}]->(:Claim)
-- - (:Provider)-[:SUBMITS {submission_date}]->(:Claim)
